"""
Model card renderer — converts a ModelCard to Markdown or HTML.

Two output formats:
  markdown — for GitHub READMEs, Hugging Face Hub model pages, and plain text
  html     — for rendered web pages, downloadable reports, and email sharing

MARKDOWN FORMAT
---------------
Follows the structure used by Hugging Face Hub model cards and Google's
Model Card Toolkit. Compatible with standard Markdown renderers.

HTML FORMAT
-----------
Self-contained single-file HTML with inline CSS. No external dependencies.
Uses a clean, professional design that prints well. Suitable for:
  - Sharing with non-technical stakeholders
  - Regulatory submissions (EU AI Act technical documentation)
  - Model risk management reviews
"""

from __future__ import annotations

from model_cards.generator import ModelCard


# ══════════════════════════════════════════════════════════════════════════
# MARKDOWN RENDERER
# ══════════════════════════════════════════════════════════════════════════

def render_markdown(card: ModelCard) -> str:
    """Renders a ModelCard to GitHub-flavoured Markdown."""
    lines = []

    def h1(t):   lines.append(f"# {t}\n")
    def h2(t):   lines.append(f"## {t}\n")
    def h3(t):   lines.append(f"### {t}\n")
    def p(t):    lines.append(f"{t}\n")
    def li(t):   lines.append(f"- {t}")
    def blank():  lines.append("")

    h1(f"🧪 Model Card — {card.model_name}")
    p(f"*Generated by Crucible ML Platform v{card.crucible_version} · {card.created_at[:10]}*")
    blank()

    # ── Overview ──────────────────────────────────────────────────────────
    h2("Model Overview")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Experiment ID | {card.experiment_id} |")
    lines.append(f"| Model family | {card.model_family} |")
    lines.append(f"| Task type | {card.task_type} |")
    lines.append(f"| Target column | {card.target_column or '—'} |")
    lines.append(f"| Created | {card.created_at[:10]} |")
    blank()

    # ── Intended use ──────────────────────────────────────────────────────
    h2("Intended Use")
    p(card.intended_use)
    blank()
    h3("Out-of-scope uses")
    for item in card.out_of_scope:
        li(item)
    blank()

    # ── Training data ─────────────────────────────────────────────────────
    h2("Training Data")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Dataset | {card.dataset_name or '—'} (ID {card.dataset_id or '—'}) |")
    lines.append(f"| Source type | {card.dataset_source_type or '—'} |")
    lines.append(f"| Rows | {card.n_training_rows or '—'} |")
    lines.append(f"| Features | {card.n_features or '—'} |")
    blank()
    if card.feature_names:
        h3("Feature list (first 20)")
        p(", ".join(f"`{f}`" for f in card.feature_names[:20]))
        blank()

    # ── Training config ───────────────────────────────────────────────────
    h2("Training Configuration")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Optimisation trials | {card.n_trials or '—'} |")
    lines.append(f"| CV folds | {card.cv_folds or 5} |")
    if card.best_params:
        for k, v in list(card.best_params.items())[:6]:
            lines.append(f"| {k} | {v} |")
    blank()

    # ── Performance ───────────────────────────────────────────────────────
    h2("Evaluation Results")
    if card.cv_score is not None:
        p(f"**Cross-validation {card.cv_metric}:** {card.cv_score:.4f}")
        blank()
    if card.metrics:
        h3("Holdout metrics")
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        for m in card.metrics:
            lines.append(f"| {m.name} | {m.value:.4f} |")
        blank()

    # ── Feature importances ───────────────────────────────────────────────
    if card.feature_importances:
        h2("Feature Importances (SHAP)")
        lines.append("| Rank | Feature | Mean |SHAP| |")
        lines.append("|---|---|---|")
        for i, fi in enumerate(card.feature_importances[:10], 1):
            bar = "█" * max(1, int(fi.mean_abs_shap * 20 / max(card.feature_importances[0].mean_abs_shap, 1e-9)))
            lines.append(f"| {i} | `{fi.feature}` | {fi.mean_abs_shap:.4f} {bar} |")
        blank()

    # ── Fairness ──────────────────────────────────────────────────────────
    h2("Fairness Assessment")
    if not card.fairness_assessed:
        p("⚠️ No fairness analysis has been performed for this model.")
    else:
        severity_emoji = {
            "acceptable": "✅", "marginal": "⚠️", "significant": "🔶", "severe": "🚨"
        }
        emoji = severity_emoji.get(card.fairness_overall_severity or "", "ℹ️")
        p(f"{emoji} **Overall severity:** {card.fairness_overall_severity or 'unknown'}")
        blank()
        if card.fairness_entries:
            lines.append("| Attribute | Dem. Parity Δ | Equal Opp. Δ | Disparate Impact | Severity |")
            lines.append("|---|---|---|---|---|")
            for fe in card.fairness_entries:
                lines.append(
                    f"| {fe.attribute} | {fe.demographic_parity_diff:.4f} | "
                    f"{fe.equal_opportunity_diff:.4f} | "
                    f"{fe.disparate_impact_ratio:.4f} | {fe.severity} |"
                )
            blank()
    blank()

    # ── Data contract ─────────────────────────────────────────────────────
    if card.contract_version:
        h2("Data Contract")
        lines.append("| Field | Value |")
        lines.append("|---|---|")
        lines.append(f"| Contract version | {card.contract_version} |")
        lines.append(f"| Columns covered | {card.contract_n_columns or '—'} |")
        lines.append(f"| Numeric tolerance | ±{(card.contract_tolerance or 0) * 100:.0f}% |")
        blank()

    # ── Limitations ───────────────────────────────────────────────────────
    h2("Limitations")
    for item in card.limitations:
        li(item)
    blank()

    # ── Ethical considerations ────────────────────────────────────────────
    h2("Ethical Considerations")
    for item in card.ethical_considerations:
        li(item)
    blank()

    # ── Recommendations ───────────────────────────────────────────────────
    h2("Recommendations")
    for item in card.recommendations:
        li(item)
    blank()

    # ── Footer ────────────────────────────────────────────────────────────
    p("---")
    p(f"*Generated by [Crucible ML Platform](https://github.com/yapovazhnyi-blip/analytics-and-ml-portfolio) · Experiment {card.experiment_id}*")

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════
# HTML RENDERER
# ══════════════════════════════════════════════════════════════════════════

def render_html(card: ModelCard) -> str:
    """Renders a ModelCard to self-contained HTML with inline styles."""
    md = render_markdown(card)

    severity_color = {
        "acceptable": "#27AE60", "marginal": "#F39C12",
        "significant": "#E67E22", "severe": "#E74C3C",
    }

    def _sev_badge(sev: str) -> str:
        color = severity_color.get(sev, "#95A5A6")
        return f'<span style="background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:700">{sev}</span>'

    # Build metric rows
    metric_rows = ""
    if card.metrics:
        for m in card.metrics:
            metric_rows += f"<tr><td>{m.name}</td><td><strong>{m.value:.4f}</strong></td><td>{m.split}</td></tr>"

    # Build SHAP rows
    shap_rows = ""
    max_shap = card.feature_importances[0].mean_abs_shap if card.feature_importances else 1
    for i, fi in enumerate(card.feature_importances[:10], 1):
        pct = int(fi.mean_abs_shap / max(max_shap, 1e-9) * 100)
        bar = f'<div style="width:{pct}%;height:8px;background:#3498DB;border-radius:4px"></div>'
        shap_rows += f"<tr><td>{i}</td><td><code>{fi.feature}</code></td><td>{fi.mean_abs_shap:.4f}</td><td style='width:120px'>{bar}</td></tr>"

    # Build fairness rows
    fairness_rows = ""
    for fe in card.fairness_entries:
        color = severity_color.get(fe.severity, "#95A5A6")
        fairness_rows += (
            f"<tr><td>{fe.attribute}</td>"
            f"<td>{fe.demographic_parity_diff:.4f}</td>"
            f"<td>{fe.equal_opportunity_diff:.4f}</td>"
            f"<td>{fe.disparate_impact_ratio:.4f}</td>"
            f"<td>{_sev_badge(fe.severity)}</td></tr>"
        )

    limitations_html = "".join(f"<li>{l}</li>" for l in card.limitations)
    ethical_html = "".join(f"<li>{e}</li>" for e in card.ethical_considerations)
    recs_html = "".join(f"<li>{r}</li>" for r in card.recommendations)
    features_html = "".join(f"<code style='margin:2px 4px;padding:2px 6px;background:#f5f5f5;border-radius:4px'>{f}</code>" for f in card.feature_names[:20])

    sev_color = severity_color.get(card.fairness_overall_severity or "", "#95A5A6")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Model Card — {card.model_name}</title>
<style>
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:900px;margin:40px auto;padding:0 24px;color:#1a1a2e;line-height:1.7}}
  h1{{color:#2c3e50;border-bottom:3px solid #3498DB;padding-bottom:12px}}
  h2{{color:#2c3e50;margin-top:40px;border-left:4px solid #3498DB;padding-left:12px}}
  h3{{color:#555}}
  table{{width:100%;border-collapse:collapse;margin:16px 0}}
  th{{background:#2c3e50;color:#fff;padding:10px 14px;text-align:left}}
  td{{padding:8px 14px;border-bottom:1px solid #eee}}
  tr:hover{{background:#f8f9ff}}
  .badge{{display:inline-block;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:700}}
  .meta{{color:#7f8c8d;font-size:13px;margin-top:-8px}}
  .card-section{{background:#f8f9fa;border-radius:8px;padding:20px;margin:16px 0}}
  code{{background:#f0f0f0;padding:2px 6px;border-radius:4px;font-family:monospace;font-size:13px}}
  ul{{padding-left:20px}}
  li{{margin:6px 0}}
  .warning{{background:#fff3cd;border-left:4px solid #F39C12;padding:12px 16px;border-radius:4px}}
  .error{{background:#fde8e8;border-left:4px solid #E74C3C;padding:12px 16px;border-radius:4px}}
  .ok{{background:#d4edda;border-left:4px solid #27AE60;padding:12px 16px;border-radius:4px}}
  .no-print{{color:#3498DB;font-style:italic}}
  @media print{{.no-print{{display:none}}}}
</style>
</head>
<body>
<h1>🧪 Model Card</h1>
<p class="meta">Generated by <strong>Crucible ML Platform</strong> v{card.crucible_version} · {card.created_at[:10]}</p>

<div class="card-section">
<table>
<tr><th colspan="2">{card.model_name}</th></tr>
<tr><td>Experiment ID</td><td><strong>#{card.experiment_id}</strong></td></tr>
<tr><td>Model family</td><td><strong>{card.model_family}</strong></td></tr>
<tr><td>Task type</td><td>{card.task_type}</td></tr>
<tr><td>Target column</td><td><code>{card.target_column or '—'}</code></td></tr>
<tr><td>Created</td><td>{card.created_at[:10]}</td></tr>
</table>
</div>

<h2>📋 Intended Use</h2>
<p>{card.intended_use}</p>
<h3>Out-of-scope uses</h3><ul>{chr(10).join(f'<li>{o}</li>' for o in card.out_of_scope)}</ul>

<h2>📊 Training Data</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>Dataset</td><td>{card.dataset_name or '—'} (ID {card.dataset_id or '—'})</td></tr>
<tr><td>Source type</td><td>{card.dataset_source_type or '—'}</td></tr>
<tr><td>Rows</td><td>{card.n_training_rows or '—'}</td></tr>
<tr><td>Features</td><td>{card.n_features or '—'}</td></tr>
</table>
{'<h3>Features</h3><p>' + features_html + '</p>' if features_html else ''}

<h2>⚙️ Training Configuration</h2>
<table>
<tr><th>Hyperparameter</th><th>Value</th></tr>
<tr><td>Optimisation trials</td><td>{card.n_trials or '—'}</td></tr>
<tr><td>CV folds</td><td>{card.cv_folds or 5}</td></tr>
{''.join(f'<tr><td>{k}</td><td>{v}</td></tr>' for k,v in list(card.best_params.items())[:6])}
</table>

<h2>📈 Evaluation Results</h2>
{'<p><strong>Cross-validation ' + card.cv_metric + ':</strong> ' + f'{card.cv_score:.4f}' + '</p>' if card.cv_score is not None else ''}
{'<h3>Holdout metrics</h3><table><tr><th>Metric</th><th>Value</th><th>Split</th></tr>' + metric_rows + '</table>' if metric_rows else ''}

{'<h2>🔍 Feature Importances (SHAP)</h2><table><tr><th>#</th><th>Feature</th><th>Mean |SHAP|</th><th>Importance</th></tr>' + shap_rows + '</table>' if shap_rows else ''}

<h2>⚖️ Fairness Assessment</h2>
{'<div class="warning"><strong>⚠️ No fairness analysis performed.</strong> Run POST /experiments/{id}/fairness before regulated deployment.</div>' if not card.fairness_assessed else
f'<div class="{"ok" if card.fairness_overall_severity == "acceptable" else "warning" if card.fairness_overall_severity in ("marginal","significant") else "error"}"><strong>Overall severity:</strong> {_sev_badge(card.fairness_overall_severity or "unknown")}</div>' +
(f'<table><tr><th>Attribute</th><th>Dem. Parity Δ</th><th>Equal Opp. Δ</th><th>Disparate Impact</th><th>Severity</th></tr>{fairness_rows}</table>' if fairness_rows else '')}

<h2>⚠️ Limitations</h2>
<ul>{limitations_html}</ul>

<h2>🤝 Ethical Considerations</h2>
<ul>{ethical_html}</ul>

<h2>✅ Recommendations</h2>
<ul>{recs_html}</ul>

<hr>
<p class="meta no-print">Generated by <a href="https://github.com/yapovazhnyi-blip/analytics-and-ml-portfolio">Crucible ML Platform</a> · Experiment {card.experiment_id}</p>
</body>
</html>"""
