"""add_anthropic_key_encrypted_to_users

Revision ID: 00ba38f8b8c6
Revises: 92d34d6b1edb
Create Date: 2026-06-18 20:08:57.846948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ba38f8b8c6'
down_revision: Union[str, Sequence[str], None] = '92d34d6b1edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anthropic_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_key_encrypted')
    # ### end Alembic commands ###
