"""add_agent_traces_and_registered_agents

Revision ID: 05829ccb9b71
Revises: 00ba38f8b8c6
Create Date: 2026-06-19 04:34:09.379744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05829ccb9b71'
down_revision: Union[str, Sequence[str], None] = '00ba38f8b8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('n_tool_calls', sa.Integer(), nullable=False),
    sa.Column('elapsed_secs', sa.Float(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('score_pending', sa.Boolean(), nullable=False),
    sa.Column('used_in_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_agent_type'), 'agent_traces', ['agent_type'], unique=False)
    op.create_table('registered_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_model', sa.String(length=200), nullable=False),
    sa.Column('adapter_path', sa.String(length=1024), nullable=True),
    sa.Column('bundle_path', sa.String(length=1024), nullable=True),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('n_training_traces', sa.Integer(), nullable=False),
    sa.Column('training_method', sa.String(length=20), nullable=False),
    sa.Column('benchmark_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_agents_name'), 'registered_agents', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_agents_name'), table_name='registered_agents')
    op.drop_table('registered_agents')
    op.drop_index(op.f('ix_agent_traces_agent_type'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
