"""add_forecast_jobs_table

Revision ID: 94dfcd19eae0
Revises: c8a83dcf3dcd
Create Date: 2026-06-17 12:37:07.412170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dfcd19eae0'
down_revision: Union[str, Sequence[str], None] = 'c8a83dcf3dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('date_column', sa.String(length=255), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('best_family', sa.String(length=50), nullable=True),
    sa.Column('cv_mape', sa.Float(), nullable=True),
    sa.Column('cv_rmse', sa.Float(), nullable=True),
    sa.Column('cv_mae', sa.Float(), nullable=True),
    sa.Column('n_trials_completed', sa.Integer(), nullable=True),
    sa.Column('elapsed_secs', sa.Float(), nullable=True),
    sa.Column('forecast_json', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_jobs_job_id'), 'forecast_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_jobs_job_id'), table_name='forecast_jobs')
    op.drop_table('forecast_jobs')
    # ### end Alembic commands ###
