"""add_fine_tune_jobs_table

Revision ID: c8a83dcf3dcd
Revises: 4a643acdcd4f
Create Date: 2026-06-17 07:55:34.288528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a83dcf3dcd'
down_revision: Union[str, Sequence[str], None] = '4a643acdcd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tune_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('base_model_id', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('dataset_format', sa.String(length=20), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('lora_config_json', sa.Text(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('use_qlora', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('adapter_path', sa.String(length=1024), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('elapsed_secs', sa.Float(), nullable=True),
    sa.Column('hub_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_tune_jobs_job_id'), 'fine_tune_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fine_tune_jobs_job_id'), table_name='fine_tune_jobs')
    op.drop_table('fine_tune_jobs')
    # ### end Alembic commands ###
