"""add_retraining_pipeline_and_lifecycle_stage

Revision ID: e7dff32ed0a8
Revises: 05829ccb9b71
Create Date: 2026-06-19 13:20:03.823027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dff32ed0a8'
down_revision: Union[str, Sequence[str], None] = '05829ccb9b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retraining_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_dataset_id', sa.Integer(), nullable=False),
    sa.Column('latest_dataset_id', sa.Integer(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('drift_severity_trigger', sa.String(length=20), nullable=False),
    sa.Column('promotion_margin', sa.Float(), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('cv_folds', sa.Integer(), nullable=False),
    sa.Column('check_interval_hours', sa.Float(), nullable=True),
    sa.Column('production_experiment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['latest_dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_policies_name'), 'retraining_policies', ['name'], unique=True)
    op.create_table('retraining_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('current_dataset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('drift_checked', sa.Boolean(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_report_json', sa.Text(), nullable=True),
    sa.Column('retrain_triggered', sa.Boolean(), nullable=False),
    sa.Column('new_experiment_id', sa.Integer(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('promotion_reason', sa.Text(), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('elapsed_secs', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['new_experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['retraining_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_runs_policy_id'), 'retraining_runs', ['policy_id'], unique=False)
    op.add_column('experiments', sa.Column('lifecycle_stage', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'lifecycle_stage')
    op.drop_index(op.f('ix_retraining_runs_policy_id'), table_name='retraining_runs')
    op.drop_table('retraining_runs')
    op.drop_index(op.f('ix_retraining_policies_name'), table_name='retraining_policies')
    op.drop_table('retraining_policies')
    # ### end Alembic commands ###
